<a href="https://colab.research.google.com/github/dlguswn3659/2020_Image_Lab/blob/master/pytorch01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[9.5786e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8514, 0.3889, 0.4393],
        [0.5985, 0.2058, 0.9969],
        [0.4126, 0.1251, 0.8850],
        [0.8253, 0.0971, 0.6880],
        [0.5220, 0.4585, 0.4803]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1705,  0.9976, -0.1905],
        [ 0.7184, -0.4969,  0.3535],
        [ 0.4331,  0.4513,  0.3819],
        [-0.1865,  0.4812,  0.0924],
        [-0.2184, -0.1768, -2.3957]])


In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.4638,  1.4383,  0.5900],
        [ 1.5766,  0.3434,  1.0760],
        [ 1.2004,  1.2411,  0.9590],
        [ 0.8025,  0.5829,  0.3277],
        [-0.1449, -0.0080, -1.9296]])


In [10]:
print(torch.add(x, y))

tensor([[ 0.4638,  1.4383,  0.5900],
        [ 1.5766,  0.3434,  1.0760],
        [ 1.2004,  1.2411,  0.9590],
        [ 0.8025,  0.5829,  0.3277],
        [-0.1449, -0.0080, -1.9296]])


In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.4638,  1.4383,  0.5900],
        [ 1.5766,  0.3434,  1.0760],
        [ 1.2004,  1.2411,  0.9590],
        [ 0.8025,  0.5829,  0.3277],
        [-0.1449, -0.0080, -1.9296]])
