<a href="https://colab.research.google.com/github/dlguswn3659/2020_Image_Lab/blob/master/pytorch01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[9.5786e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8514, 0.3889, 0.4393],
        [0.5985, 0.2058, 0.9969],
        [0.4126, 0.1251, 0.8850],
        [0.8253, 0.0971, 0.6880],
        [0.5220, 0.4585, 0.4803]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1705,  0.9976, -0.1905],
        [ 0.7184, -0.4969,  0.3535],
        [ 0.4331,  0.4513,  0.3819],
        [-0.1865,  0.4812,  0.0924],
        [-0.2184, -0.1768, -2.3957]])


In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.4638,  1.4383,  0.5900],
        [ 1.5766,  0.3434,  1.0760],
        [ 1.2004,  1.2411,  0.9590],
        [ 0.8025,  0.5829,  0.3277],
        [-0.1449, -0.0080, -1.9296]])


In [10]:
print(torch.add(x, y))

tensor([[ 0.4638,  1.4383,  0.5900],
        [ 1.5766,  0.3434,  1.0760],
        [ 1.2004,  1.2411,  0.9590],
        [ 0.8025,  0.5829,  0.3277],
        [-0.1449, -0.0080, -1.9296]])


In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.4638,  1.4383,  0.5900],
        [ 1.5766,  0.3434,  1.0760],
        [ 1.2004,  1.2411,  0.9590],
        [ 0.8025,  0.5829,  0.3277],
        [-0.1449, -0.0080, -1.9296]])


In [12]:
y.add_(x)
print(y)

tensor([[ 0.4638,  1.4383,  0.5900],
        [ 1.5766,  0.3434,  1.0760],
        [ 1.2004,  1.2411,  0.9590],
        [ 0.8025,  0.5829,  0.3277],
        [-0.1449, -0.0080, -1.9296]])


In [13]:
print(x[:, 1])

tensor([ 0.9976, -0.4969,  0.4513,  0.4812, -0.1768])


In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([2.4096])
2.4095749855041504


In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [20]:
print(torch.cuda.is_available())
if torch.cuda.is_available():
  device = torch.device("cuda")
  y = torch.ones_like(x, device=device)
  x = x.to(device)
  z = x + y
  print(z)
  print(z.to("cpu", torch.double))

False


# **오토 그라드 : 자동 미분**
PyTorch의 모든 신경망의 중심은 autograd패키지이다. 먼저 이것을 간단히 방문해 보자. 그러면 우리는 첫 신경망을 훈련시키는 것으로 간다.

이 autograd패키지는 Tensor의 모든 작업에 대한 자동 차별화를 제공한다. 

In [13]:
import torch

x = torch.ones(2, 2, requires_grad=True)
print(x)

y = x + 2
print(y)

print(y.grad_fn)

z = y*y*3
out = z.mean()

print(z, out)

a = torch.randn(2, 2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
False
True


In [14]:
# print(x)
# print(out)

out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [15]:
x = torch.randn(3, requires_grad=True)

y = x*2
while y.data.norm() < 1000:
  y = y*2

print(y)

tensor([ 588.0714,   71.6271, 1181.8999], grad_fn=<MulBackward0>)


In [16]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([5.1200e+01, 5.1200e+02, 5.1200e-02])


In [18]:
print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
  print((x ** 2).requires_grad)

print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
True
False
True
False
tensor(True)
